### ISSUE TITLE
Incompatibility with Mod 'Inventorio'

### ISSUE THREAD

**Issue by JustCallMeAz** [B1n-ry/Youre-in-grave-danger#157]
Hi, 
Unlike what the mod description is saying, i'm facing an issue with 'Inventorio' while having 'You're in grave danger'.

It cause my game to crash.

Here is a short crash log :
[crash log : inventorio youre in grave danger.txt](https://github.com/RubixDev/Inventorio/files/14736309/crash.inventorio.youre.in.grave.danger.txt)

**Comment by B1n-ry** [comment]
Should be fixed in yigd 2.0.0-beta.11. Thank you for reporting, and let me know if it will still cause an error

**Comment by JustCallMeAz** [comment]
@B1n-ry I'm a bit lost. 2.0.0-beta.10. wasn't working, I saw your update just after opening this ticket, so I made it to beta.11. (I haven't deleted config file before to update it if that does matter), then it was working !

But then, I try to downgrade to beta.10. (this time I deleted the config file before, still don't know if that does matter), and then this version that makes me crashed was working, with bugs but no crash.

I upgraded it again to beta.11. , now it's working like a charm, no bugs, no crash !

Your addition to the game is fantastic, sincerely thanks for it !
